#!/bin/bash
for i in `cat ip.txt`
do
ping=`ping -c 1 $i|grep loss|awk '{print $6}'|awk -F "%" '{print $1}'>/dev/null`;
if [[ $ping -eq 100 ]];then
echo ping $i  fail
else
echo ping $i  ok
fi
done
一开始比较部分，总是报错，后来改成[[ ]],错误消失。
如果变量值为空，那么就成了 [ = "OK"] ，显然 [ 和 "OK" 不相等并且缺少了 [ 符号，所以报了这样的错误。
当然不总是出错，如果变量值不为空，程序就正常了。
